### ISSUE TITLE
Cant open Console. 

### ISSUE THREAD

**Issue by karorogunso** [igromanru/CheatConsoleCommands-UE4SS-AF#1]
![image](https://github.com/user-attachments/assets/9348e4b5-8412-4c38-8397-810765304c29)
During the new patch today. 
They made F10 become Toggle HUD and Even Changed Toggle HUD to something else. 
F10 still doesn't work.

Even Change it > Restart a game > Try Double check that F10 doesn't assign to Toggle HUD still doesn't work.

AF Version: Hotfix 0.9.1.11736 (Run on Both DX11 and DX12)
UE4SS Version: v3.0.1
CCCAF Version: 1.9.1 and commit 4dfd4ff

**Comment by igromanru** [comment]
![firefox_SRmtCDhJMb](https://github.com/user-attachments/assets/c440305c-7f10-476c-8862-05ef93bd278e)

Have you upgraded UE4SS to this version?
https://www.nexusmods.com/abioticfactor/mods/35

EDIT: If you still encounter the issue, please post the content of **UE4SS.log** after starting the game.

**Comment by karorogunso** [comment]
Yeah it's working now. thank for the info.
